import type { Metadata } from 'next'
import { Inter, Poppins, Montserrat } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
export const poppins = Poppins({ subsets: ['latin'], weight: ["500"] },)
export const montserrat = Poppins({ subsets: ['latin'], weight: ["400"] },)

export const metadata: Metadata = {
  title: 'Recipe Box',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  )
}
