export interface Ingredient {
  title: string;
  image: string;
  selected: string[];
  data: string[];
}
export const Ingredients: Ingredient[] = [
  {
    title: "Pantry Essentials",
    image: "pantry-essentials",
    selected: [],
    data: [
      "Flour",
      "Sugar",
      "Salt",
      "Pepper",
      "Olive Oil",
      "Vegetable Oil",
      "Balsamic Vinegar",
      "Soy Sauce",
      "Honey",
      "Maple Syrup",
      "Rice",
      "Pasta",
      "Canned Tomatoes",
      "Tomato Sauce",
      "Canned Beans",
      "Lentils",
      "Quinoa",
      "Oats",
      "Cereal",
      "Peanut Butter",
      "Jam",
      "Canned Tuna",
      "Canned Salmon",
      "Chicken Broth",
      "Beef Broth",
      "Dried Herbs",
      "Spices",
      "All-Purpose Seasoning",
      "Onions",
      "Garlic",
      "Potatoes",
      "Canned Vegetables",
      "Frozen Vegetables",
      "Milk",
      "Eggs",
      "Cheese",
      "Butter",
      "Bread",
    ],
  },
  {
    title: "Vegetables & Greens",
    image: "vegetables-and-greens",
    selected: [],
    data: [
      "Broccoli",
      "Spinach",
      "Carrot",
      "Kale",
      "Cucumber",
      "Bell Pepper",
      "Tomato",
      "Lettuce",
      "Cabbage",
      "Cauliflower",
      "Zucchini",
      "Radish",
      "Eggplant",
      "Asparagus",
      "Brussels Sprouts",
      "Green Beans",
      "Peas",
      "Sweet Potato",
      "Onion",
      "Garlic",
      "Ginger",
      "Leek",
      "Artichoke",
      "Celery",
      "Pumpkin",
      "Butternut Squash",
      "Chard",
      "Beet",
      "Turnip",
      "Collard Greens",
      "Romaine Lettuce",
      "Arugula",
      "Watercress",
      "Okra",
      "Cilantro",
      "Parsley",
      "Dill",
      "Mint",
      "Thyme",
      "Rosemary",
      "Basil",
      "Chives",
      "Coriander",
      "Sage",
      "Oregano",
      "Fennel",
      "Mustard Greens",
      "Water Spinach",
    ],
  },
  {
    title: "Fruits",
    image: "fruits",
    selected: [],
    data: [
      "Apple",
      "Banana",
      "Orange",
      "Grapes",
      "Strawberry",
      "Watermelon",
      "Pineapple",
      "Mango",
      "Kiwi",
      "Blueberry",
      "Peach",
      "Cherry",
      "Pear",
      "Plum",
      "Raspberry",
      "Apricot",
      "Avocado",
      "Pomegranate",
      "Cranberry",
      "Coconut",
    ],
  },
  {
    title: "Mushroom",
    image: "mushroom",
    selected: [],
    data: [
      "Agaricus blazei",
      "Amanita muscaria",
      "Armillaria mellea",
      "Boletus edulis",
      "Cordyceps sinensis",
      "Enokitake",
      "Flammulina velutipes",
      "Ganoderma lucidum",
      "Grifola frondosa",
      "Hericium erinaceus",
      "Hypholoma sublateritium",
      "Lentinula edodes",
      "Maitake",
      "Marasmius oreades",
      "Morchella esculenta",
      "Oyster Mushroom",
      "Pleurotus citrinopileatus",
      "Pleurotus eryngii",
      "Pleurotus ostreatus",
      "Pleurotus pulmonarius",
      "Polyporus squamosus",
      "Psilocybe cubensis",
      "Psilocybe semilanceata",
      "Reishi",
      "Schizophyllum commune",
      "Shaggy Mane",
      "Shiitake",
      "Sparassis crispa",
      "Stropharia rugosoannulata",
      "Trametes versicolor",
      "Tricholoma matsutake",
      "Turkey Tail",
      "Volvariella volvacea",
      "White Button Mushroom",
      "Xerocomus badius",
      "Yellow Morel",
      "Zhu Ling",
    ],
  },
  {
    title: "Berries",
    image: "berries",
    selected: [],
    data: [
      "Acai Berry",
      "Bilberry",
      "Blackberry",
      "Blueberry",
      "Chokeberry",
      "Cloudberry",
      "Cranberry",
      "Crowberry",
      "Currant",
      "Elderberry",
      "Goji Berry",
      "Gooseberry",
      "Huckleberry",
      "Juniper Berry",
      "Lingonberry",
      "Loganberry",
      "Maqui Berry",
      "Mulberry",
      "Nannyberry",
      "Raspberry",
      "Salmonberry",
      "Sea Buckthorn Berry",
      "Serviceberry",
      "Saskatoon Berry",
      "Strawberry",
      "Sunberry",
      "Tayberry",
      "Thimbleberry",
      "Uva Ursi Berry",
      "Wolfberry",
      "Youngberry",
      "Amla Berry",
      "Barberry",
      "Buffaloberry",
      "Goumi Berry",
      "Hackberry",
      "Jostaberry",
      "Kiwiberry",
      "Marionberry",
    ],
  },
  {
    title: "Nuts and Seeds",
    image: "nuts-and-seeds",
    selected: [],
    data: [
      "Almond",
      "Brazil Nut",
      "Cashew",
      "Chia Seed",
      "Coconut",
      "Flaxseed",
      "Hazelnut",
      "Hemp Seed",
      "Macadamia Nut",
      "Pecan",
      "Pine Nut",
      "Pistachio",
      "Poppy Seed",
      "Pumpkin Seed",
      "Sesame Seed",
      "Sunflower Seed",
      "Walnut",
      "Amaranth",
      "Beechnut",
      "Buckwheat",
      "Chestnut",
      "Fennel Seed",
      "Ginkgo Nut",
      "Lupin Seed",
      "Millet",
      "Peanut",
      "Quinoa",
      "Safflower Seed",
      "Soybean",
      "Spelt",
      "Tigernut",
      "Watermelon Seed",
      "Flax",
      "Sunflower Kernel",
      "Pumpkin Kernel",
      "Pine Nut Kernel",
      "Chia",
      "Sesame",
      "Poppy",
    ],
  },
  {
    title: "Cheeses",
    image: "cheeses",
    selected: [],
    data: [
      "Cheddar",
      "Parmesan",
      "Gouda",
      "Brie",
      "Camembert",
      "Blue Cheese",
      "Swiss",
      "Feta",
      "Gruyère",
      "Mozzarella",
      "Provolone",
      "Havarti",
      "Gorgonzola",
      "Roquefort",
      "Manchego",
      "Emmental",
      "Havarti",
      "Colby",
      "Monterey Jack",
      "Pepper Jack",
      "Muenster",
      "Limburger",
      "Fontina",
      "Goat Cheese",
      "Burrata",
      "Ricotta",
      "Gouda",
      "Edam",
      "Asiago",
      "Jarlsberg",
      "Pecorino Romano",
      "Cottage Cheese",
      "Queso Fresco",
      "Queso Blanco",
      "Boursin",
      "Stilton",
      "Taleggio",
      "Humboldt Fog",
      "Wensleydale",
    ],
  },
  {
    title: "Meats",
    image: "meats",
    selected: [],
    data: [
      "Chicken",
      "Beef",
      "Pork",
      "Lamb",
      "Turkey",
      "Duck",
      "Venison",
      "Salmon",
      "Tuna",
      "Shrimp",
      "Crab",
      "Lobster",
      "Bacon",
      "Sausage",
      "Ham",
      "Pepperoni",
      "Salami",
      "Prosciutto",
      "Chorizo",
      "Ground Beef",
      "Ground Turkey",
      "Ground Chicken",
      "Veal",
      "Bison",
      "Quail",
      "Goose",
      "Trout",
      "Halibut",
      "Cod",
      "Sardines",
      "Mussels",
      "Clams",
      "Octopus",
      "Anchovies",
      "Escargot",
      "Rabbit",
      "Pheasant",
      "Kangaroo",
      "Ostrich",
      "Alligator",
    ],
  },
  {
    title: "Fishs",
    image: "fishs",
    selected: [],
    data: [
      "Salmon",
      "Tuna",
      "Trout",
      "Halibut",
      "Cod",
      "Sardines",
      "Mackerel",
      "Haddock",
      "Mahi Mahi",
      "Swordfish",
      "Barramundi",
      "Perch",
      "Catfish",
      "Grouper",
      "Snapper",
      "Sea Bass",
      "Flounder",
      "Carp",
      "Rainbow Trout",
      "Arctic Char",
      "Yellowtail",
      "Red Snapper",
      "Striped Bass",
      "Bluefish",
      "Cobia",
      "Rockfish",
      "Monkfish",
      "Wahoo",
      "Tilefish",
      "Pompano",
      "Branzino",
      "Turbot",
      "Albacore",
      "Skipjack",
      "Yellowfin Tuna",
      "Bream",
      "Porgy",
      "Pollock",
      "Whitefish",
      "Eel",
      "Anchovy",
    ],
  },
  {
    title: "Seafood & Seaweed",
    image: "seafood-and-seaweed",
    selected: [],
    data: [
      "Shrimp",
      "Crab",
      "Lobster",
      "Clams",
      "Mussels",
      "Oysters",
      "Scallops",
      "Squid",
      "Octopus",
      "Crayfish",
      "Caviar",
      "Anchovies",
      "Sardines",
      "Herring",
      "Smoked Salmon",
      "Trout",
      "Eel",
      "Cuttlefish",
      "Abalone",
      "Geoduck",
      "Sea Urchin",
      "Sea Cucumber",
      "Dulse",
      "Nori",
      "Kombu",
      "Wakame",
      "Arame",
      " Hijiki",
      "Agar",
      "Irish Moss",
      "Laver",
      "Bamboo Shoots",
      "Water Chestnuts",
      "Lotus Root",
      "Sea Asparagus",
      "Samphire",
      "Kelp",
      "Spirulina",
      "Chlorella",
      "Dulse",
    ],
  },
  {
    title: "Herbs & Spices",
    image: "herbs-and-spices",
    selected: [],
    data: [
      "Basil",
      "Cilantro",
      "Dill",
      "Rosemary",
      "Thyme",
      "Oregano",
      "Sage",
      "Parsley",
      "Mint",
      "Chives",
      "Coriander",
      "Tarragon",
      "Marjoram",
      "Chervil",
      "Cumin",
      "Paprika",
      "Turmeric",
      "Cayenne Pepper",
      "Black Pepper",
      "White Pepper",
      "Cardamom",
      "Cinnamon",
      "Nutmeg",
      "Cloves",
      "Allspice",
      "Ginger",
      "Garlic",
      "Onion Powder",
      "Mustard Seed",
      "Fenugreek",
      "Fennel Seed",
      "Caraway Seed",
      "Celery Seed",
      "Bay Leaf",
      "Dill Seed",
      "Saffron",
      "Vanilla",
      "Star Anise",
      "Sumac",
      "Smoked Paprika",
    ],
  },
  {
    title: "Grains & Cereals",
    image: "grains-and-cereals",
    selected: [],
    data: [
      "Rice",
      "Quinoa",
      "Oats",
      "Barley",
      "Buckwheat",
      "Couscous",
      "Millet",
      "Farro",
      "Amaranth",
      "Spelt",
      "Bulgur",
      "Polenta",
      "Wild Rice",
      "Sorghum",
      "Teff",
      "Kamut",
      "Freekeh",
      "Wheat Berries",
      "Rye",
      "Cornmeal",
      "Steel-Cut Oats",
      "Pearl Barley",
      "Brown Rice",
      "White Rice",
      "Basmati Rice",
      "Jasmine Rice",
      "Arborio Rice",
      "Black Rice",
      "Red Rice",
      "Yellow Cornmeal",
      "White Cornmeal",
      "Quinoa Flakes",
      "Quinoa Puffs",
      "Bran Flakes",
      "Oat Bran",
      "Granola",
      "Chia Seeds",
      "Flax Seeds",
      "Hemp Seeds",
      "Puffed Rice",
    ],
  },
  {
    title: "Bread & SaltySnacks",
    image: "bread-and-saltysnacks",
    selected: [],
    data: [
      "Baguette",
      "Sourdough",
      "Whole Wheat Bread",
      "Multigrain Bread",
      "Rye Bread",
      "Pumpernickel",
      "Ciabatta",
      "Focaccia",
      "Naan",
      "Pita Bread",
      "Brioche",
      "English Muffin",
      "Crusty White Bread",
      "Bagel",
      "Pretzel",
      "Tortilla Chips",
      "Potato Chips",
      "Pita Chips",
      "Rice Cakes",
      "Popcorn",
      "Cheese Puffs",
      "Crackers",
      "Pretzel Sticks",
      "Flatbread",
      "Grissini",
      "Melba Toast",
      "Saltines",
      "Crostini",
      "Matzo",
      "Rye Crispbread",
      "Cornbread",
      "Garlic Bread",
      "Cheese Breadsticks",
      "Pretzel Rolls",
      "Salted Peanuts",
      "Cashews",
      "Pistachios",
      "Pretzel Nuggets",
      "Cheese Crackers",
    ],
  },
  {
    title: "Canned Food",
    image: "canned-food",
    selected: [],
    data: [
      "Canned Tomatoes",
      "Canned Corn",
      "Canned Green Beans",
      "Canned Peas",
      "Canned Carrots",
      "Canned Mixed Vegetables",
      "Canned Spinach",
      "Canned Asparagus",
      "Canned Mushrooms",
      "Canned Artichoke Hearts",
      "Canned Black Beans",
      "Canned Kidney Beans",
      "Canned Chickpeas",
      "Canned Pinto Beans",
      "Canned Lentils",
      "Canned Refried Beans",
      "Canned Salmon",
      "Canned Tuna",
      "Canned Sardines",
      "Canned Anchovies",
      "Canned Chicken",
      "Canned Turkey",
      "Canned Ham",
      "Canned Corned Beef",
      "Canned Spam",
      "Canned Soup (Various Flavors)",
      "Canned Chili",
      "Canned Stew",
      "Canned Ravioli",
      "Canned Spaghetti",
      "Canned Fruit Cocktail",
      "Canned Pineapple",
      "Canned Peaches",
      "Canned Pears",
      "Canned Mandarin Oranges",
      "Canned Coconut Milk",
      "Canned Evaporated Milk",
      "Canned Condensed Milk",
      "Canned Pumpkin",
      "Canned Pie Filling",
    ],
  },
  {
    title: "Soups StewsStocks",
    image: "soups-stewsstocks",
    selected: [],
    data: [
      "Chicken Noodle Soup",
      "Tomato Soup",
      "Minestrone Soup",
      "Clam Chowder",
      "Vegetable Soup",
      "Split Pea Soup",
      "Lentil Soup",
      "Beef Stew",
      "Chicken Stew",
      "Vegetarian Stew",
      "Chili",
      "Gumbo",
      "French Onion Soup",
      "Miso Soup",
      "Matzo Ball Soup",
      "Pumpkin Soup",
      "Butternut Squash Soup",
      "Potato Leek Soup",
      "Corn Chowder",
      "Carrot Ginger Soup",
      "Cabbage Soup",
      "Borscht",
      "Gazpacho",
      "Chowder",
      "Broccoli Cheddar Soup",
      "Tortilla Soup",
      "Ramen",
      "Pho",
      "Tom Yum Soup",
      "Tom Kha Soup",
      "Beef Stock",
      "Chicken Stock",
      "Vegetable Stock",
      "Fish Stock",
      "Mushroom Stock",
      "Clam Stock",
      "Shrimp Stock",
      "Lobster Stock",
      "Turkey Stock",
      "Bone Broth",
    ],
  },
  {
    title: "Desserts & SweetSnacks",
    image: "desserts-and-sweetsnacks",
    selected: [],
    data: [
      "Chocolate Cake",
      "Vanilla Cupcakes",
      "Strawberry Shortcake",
      "Cheesecake",
      "Brownies",
      "Cookies (Various Flavors)",
      "Ice Cream (Various Flavors)",
      "Fruit Salad",
      "Peach Cobbler",
      "Apple Pie",
      "Chocolate Chip Muffins",
      "Cinnamon Rolls",
      "Donuts",
      "Eclairs",
      "Tiramisu",
      "Panna Cotta",
      "Creme Brulee",
      "Lemon Bars",
      "Fudge",
      "Rice Pudding",
      "Banana Bread",
      "Key Lime Pie",
      "Pecan Pie",
      "Cannoli",
      "Chocolate Covered Strawberries",
      "Macarons",
      "Baklava",
      "Churros",
      "Gelato",
      "Sorbet",
      "Mochi Ice Cream",
      "Truffles",
      "Pralines",
      "Rocky Road",
      "Caramel Popcorn",
      "Marshmallows",
      "Cotton Candy",
      "Gummy Bears",
      "Jelly Beans",
    ],
  },
  {
    title: "Condiments",
    image: "condiments",
    selected: [],
    data: [
      "Ketchup",
      "Mustard",
      "Mayonnaise",
      "Soy Sauce",
      "Worcestershire Sauce",
      "Hot Sauce",
      "Barbecue Sauce",
      "Ranch Dressing",
      "Thousand Island Dressing",
      "Honey Mustard",
      "Maple Syrup",
      "Salsa",
      "Guacamole",
      "Pesto",
      "Tahini",
      "Hummus",
      "Horseradish",
      "Wasabi",
      "Mirin",
      "Fish Sauce",
      "Oyster Sauce",
      "Sweet Chili Sauce",
      "Hoisin Sauce",
      "Sriracha",
      "Tzatziki",
      "Chutney",
      "Relish",
      "Pickles",
      "Olives",
      "Capers",
      "Sour Cream",
      "Cranberry Sauce",
      "Jam",
      "Peanut Butter",
      "Nutella",
      "Marmite",
      "Sesame Oil",
      "Balsamic Vinegar",
      "Apple Cider Vinegar",
      "Dijon Mustard",
    ],
  },
  {
    title: "Oils & Fats",
    image: "oils-and-fats",
    selected: [],
    data: [
      "Olive Oil",
      "Vegetable Oil",
      "Canola Oil",
      "Coconut Oil",
      "Sesame Oil",
      "Peanut Oil",
      "Sunflower Oil",
      "Corn Oil",
      "Grapeseed Oil",
      "Avocado Oil",
      "Flaxseed Oil",
      "Walnut Oil",
      "Truffle Oil",
      "Clarified Butter (Ghee)",
      "Butter",
      "Margarine",
      "Shortening",
      "Lard",
      "Duck Fat",
      "Chicken Fat (Schmaltz)",
      "Beef Tallow",
      "Palm Oil",
      "Hazelnut Oil",
      "Almond Oil",
      "Macadamia Nut Oil",
      "Pistachio Oil",
      "Camelina Oil",
      "Argan Oil",
      "Hemp Oil",
      "Chia Seed Oil",
      "Emu Oil",
      "Bacon Fat",
      "Goose Fat",
      "Safflower Oil",
      "Rice Bran Oil",
      "Black Seed Oil",
      "Pumpkin Seed Oil",
      "Emu Oil",
      "Fish Oil",
      "Krill Oil",
    ],
  },
  {
    title: "Baking Ingredients",
    image: "baking-ingredients",
    selected: [],
    data: [
      "All-Purpose Flour",
      "Whole Wheat Flour",
      "Baking Powder",
      "Baking Soda",
      "Yeast",
      "Sugar",
      "Brown Sugar",
      "Powdered Sugar",
      "Honey",
      "Maple Syrup",
      "Molasses",
      "Vanilla Extract",
      "Almond Extract",
      "Cocoa Powder",
      "Chocolate Chips",
      "Nuts (Various Types)",
      "Dried Fruits",
      "Raisins",
      "Coconut Flakes",
      "Oats",
      "Cornmeal",
      "Cream of Tartar",
      "Shortening",
      "Butter",
      "Vegetable Oil",
      "Eggs",
      "Milk",
      "Buttermilk",
      "Yogurt",
      "Sour Cream",
      "Cream Cheese",
      "Salt",
      "Cinnamon",
      "Nutmeg",
      "Cloves",
      "Ginger",
      "Allspice",
      "Cardamom",
      "Pumpkin Puree",
      "Food Coloring",
    ],
  },
  {
    title: "Seasonings & SpiceBlends",
    image: "seasonings-and-spiceblends",
    selected: [],
    data: [
      "Salt",
      "Black Pepper",
      "Garlic Powder",
      "Onion Powder",
      "Cayenne Pepper",
      "Paprika",
      "Chili Powder",
      "Cumin",
      "Coriander",
      "Turmeric",
      "Ginger",
      "Cinnamon",
      "Nutmeg",
      "Cloves",
      "Allspice",
      "Cardamom",
      "Thyme",
      "Rosemary",
      "Oregano",
      "Basil",
      "Bay Leaves",
      "Parsley",
      "Dill",
      "Sage",
      "Tarragon",
      "Marjoram",
      "Chives",
      "Curry Powder",
      "Garam Masala",
      "Italian Seasoning",
      "Herbes de Provence",
      "Cajun Seasoning",
      "Chinese Five Spice",
      "Old Bay Seasoning",
      "Za'atar",
      "Adobo Seasoning",
      "Taco Seasoning",
      "Ras el Hanout",
      "Berbere",
      "Harissa",
      "Jerk Seasoning",
    ],
  },
  {
    title: "Sugar & Sweeteners",
    image: "sugar-and-sweeteners",
    selected: [],
    data: [
      "Brown Sugar",
      "Powdered Sugar",
      "Honey",
      "Maple Syrup",
      "Molasses",
      "Agave Nectar",
      "Corn Syrup",
      "Golden Syrup",
      "Coconut Sugar",
      "Date Sugar",
      "Stevia",
      "Splenda",
      "Aspartame",
      "Saccharin",
      "Monk Fruit Sweetener",
      "Xylitol",
      "Erythritol",
      "Maltitol",
      "Sorbitol",
      "Raw Sugar",
      "Turbinado Sugar",
      "Demerara Sugar",
      "Muscovado Sugar",
      "Confectioners' Sugar",
      "Cane Sugar",
      "Panela",
      "Palm Sugar",
      "Malt Syrup",
      "Rice Syrup",
      "Barley Malt Syrup",
      "High-Fructose Corn Syrup",
      "Date Syrup",
      "Birch Syrup",
      "Sorghum Syrup",
      "Blackstrap Molasses",
      "Rice Malt Syrup",
      "Coconut Nectar",
    ],
  },
  {
    title: "Poultry",
    image: "poultry",
    selected: [],
    data: [
      "Chicken (Whole)",
      "Chicken Breast",
      "Chicken Thighs",
      "Chicken Drumsticks",
      "Chicken Wings",
      "Turkey (Whole)",
      "Turkey Breast",
      "Turkey Thighs",
      "Turkey Drumsticks",
      "Turkey Wings",
      "Duck (Whole)",
      "Duck Breast",
      "Duck Legs",
      "Duck Wings",
      "Goose (Whole)",
      "Goose Breast",
      "Goose Legs",
      "Quail",
      "Pheasant",
      "Cornish Hen",
      "Guinea Fowl",
      "Squab",
      "Capons",
      "Poussin",
      "Caponette",
      "Rock Cornish Game Hen",
      "Partridge",
      "Emu",
      "Ostrich",
      "Venison (Deer)",
      "Rabbit",
      "Capon",
      "Turkey Bacon",
      "Chicken Sausage",
      "Duck Sausage",
      "Turkey Sausage",
      "Quail Eggs",
      "Duck Eggs",
      "Goose Eggs",
    ],
  },
  {
    title: "Dairy Free Meat Substitutes",
    image: "dairy-free-meat-substitutes",
    selected: [],
    data: [
      "Tofu",
      "Tempeh",
      "Seitan",
      "Textured Vegetable Protein (TVP)",
      "Jackfruit",
      "Lentils",
      "Chickpeas",
      "Black Beans",
      "Kidney Beans",
      "Cannellini Beans",
      "Pinto Beans",
      "Soy Milk",
      "Almond Milk",
      "Coconut Milk",
      "Oat Milk",
      "Rice Milk",
      "Cashew Milk",
      "Hemp Milk",
      "Flax Milk",
      "Soy Yogurt",
      "Almond Yogurt",
      "Coconut Yogurt",
      "Cashew Yogurt",
      "Rice Yogurt",
      "Plant-Based Cheese",
      "Nutritional Yeast",
      "Vegan Butter",
      "Coconut Oil",
      "Olive Oil",
      "Avocado",
      "Mushrooms",
      "Eggplant",
      "Zucchini",
      "Sweet Potato",
      "Cauliflower",
      "Quinoa",
      "Buckwheat",
      "Chia Seeds",
      "Hemp Seeds",
      "Flax Seeds",
    ],
  },
  {
    title: "Dairy & Eggs",
    image: "dairy-and-eggs",
    selected: [],
    data: [
      "Milk",
      "Whole Milk",
      "Skim Milk",
      "Buttermilk",
      "Cream",
      "Heavy Cream",
      "Half-and-Half",
      "Whipping Cream",
      "Sour Cream",
      "Yogurt",
      "Greek Yogurt",
      "Cottage Cheese",
      "Cheese (Various Types)",
      "Butter",
      "Ghee",
      "Eggs",
      "Large Eggs",
      "Medium Eggs",
      "Small Eggs",
      "Extra-Large Eggs",
      "Egg Whites",
      "Egg Yolks",
      "Whipped Cream",
      "Evaporated Milk",
      "Condensed Milk",
      "Sweetened Condensed Milk",
      "Goat Milk",
      "Sheep Milk",
      "Buttermilk Powder",
      "Powdered Milk",
      "Non-Dairy Milk (Almond, Soy, Coconut, etc.)",
      "Non-Dairy Yogurt",
      "Non-Dairy Cheese",
      "Non-Dairy Butter",
      "Non-Dairy Creamer",
      "Non-Dairy Ice Cream",
      "Non-Dairy Whipped Topping",
      "Non-Dairy Chocolate",
    ],
  },
];
